version: "3"
services:
  go:
    image: golang:1.13.8-alpine3.11
    tty: true
    volumes:
      - ../../../app/gin:/go/src/kanta-workspace
    ports:
      - 80:8090

  mysql:
    image: mysql:5.7
    volumes:
      - ../../data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8080:80
