build-php-base:
	docker build -f ./php/base/Dockerfile -t kantaroso/php_base:`date "+%Y%m%d%H%M%S"` .
build-php-laravel:
	docker build -f ./php/Laravel/Dockerfile -t php-k8s-sample::`date "+%Y%m%d%H%M%S"` .
build-go-gin:
	echo "test"
