version: "3"
services:
  php:
    image: kantaroso/php_base:20200125173742
    tty: true
    volumes:
      - ../../../app/laravel:/var/www/html
      - ../../docker/php/laravel/config/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 80:80

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8080:80
