apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-go
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: slow
  hostPath:
    path: /data/go
    type: DirectoryOrCreate
